In [23]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_csv('cookies.csv',index_col=0,sep="\t")
# df.fillna('', inplace=True)
# Isolate cookie columns
cookie_cols = df.columns

In [39]:
# Cookie rankings dict
cookie_ratings = {}
for col in df.columns:
    cookie_ratings[col] = df[col].mean()
cookie_ratings

{'Do-si-do': 6.8076923076923075,
 'Rating Count': 5.894736842105263,
 "S'mores": 5.636363636363637,
 'Samoas': 7.388888888888889,
 'Savannah Smile': 6.125,
 'Tagalong': 6.346153846153846,
 'Thin Mint': 7.107142857142857,
 'Toffee-tastic': 5.176470588235294,
 'Trefoil': 5.785714285714286,
 'User Average': 6.188993316624895}

In [37]:
# Adding 'Rating Count' and 'User Average' cols
df['Rating Count'] = df.notna().sum(axis=1)
df['User Average'] = df.mean(axis=1)
df

,Savannah Smile,Thin Mint,Do-si-do,Trefoil,Toffee-tastic,Tagalong,Samoas,S'mores,Rating Count,User Average
Name,,,,,,,,,,
Chris,6.5,6.0,7.5,7.0,5.0,8.0,9.0,7.0,8,7.111111
Colleen,8.0,9.0,6.0,5.0,5.0,7.0,8.5,5.0,8,6.833333
Derek,6.0,9.0,6.0,5.0,3.0,8.0,9.0,5.0,8,6.555556
Kevin,NaN,4.0,NaN,8.0,6.0,NaN,9.0,NaN,4,6.200000
Vi,NaN,NaN,NaN,NaN,5.0,NaN,NaN,6.0,2,4.333333
Shashin,NaN,NaN,NaN,NaN,7.0,NaN,9.0,NaN,2,6.000000
Maggie,6.0,NaN,NaN,NaN,6.0,NaN,8.0,NaN,3,5.750000
Brandon,7.0,NaN,NaN,NaN,5.0,8.0,6.0,8.0,5,6.500000
Amanda,7.0,NaN,NaN,NaN,3.0,NaN,9.0,NaN,3,5.500000
Roman*,10.0,4.0,1.0,6.0,6.0,4.0,9.0,4.0,8,5.777778
Jeff,1.0,7.0,7.0,3.0,3.0,8.0,7.0,4.0,8,5.333333
Phteven,5.0,10.0,9.0,5.0,5.0,5.0,5.0,5.0,8,6.333333
Lara,2.0,5.0,10.0,2.0,2.0,5.0,6.0,8.0,8,5.333333
Tom D,NaN,8.0,9.0,6.0,NaN,10.0,2.0,7.0,6,6.857143
Nobis,9.0,7.0,8.0,7.0,8.0,3.0,2.0,NaN,7,6.375000
Emily,NaN,7.0,8.0,7.0,8.0,NaN,8.0,NaN,5,7.166667
Varun,NaN,9.0,5.0,5.0,7.0,6.0,9.0,NaN,6,6.714286
Araba,6.0,6.5,5.0,8.0,4.0,4.5,9.0,3.0,8,6.000000
Jon Park,NaN,8.0,7.0,7.0,NaN,6.0,8.5,NaN,5,6.916667

{'Do-si-do': 6.8076923076923075,
 'Rating Count': 5.894736842105263,
 "S'mores": 5.636363636363637,
 'Samoas': 7.388888888888889,
 'Savannah Smile': 6.125,
 'Tagalong': 6.346153846153846,
 'Thin Mint': 7.107142857142857,
 'Toffee-tastic': 5.176470588235294,
 'Trefoil': 5.785714285714286,
 'User Average': 6.188993316624895}